collections:
    pywb: ./samples/cdx/

archive_paths: ./samples/warcs/

home_html: ./index.html

enable_cdx_api: True

enable_http_proxy: True

hostpaths: ['http://localhost:9080']

static_routes: {'static/default': 'pywb/static/'}

use_lxml_parser: true
